use_frameworks!
platform :ios, '11.0'

target 'FloatingTabBarController_Example' do
  pod 'FloatingTabBarController', :path => '../'
  pod 'CGMath'
  target 'FloatingTabBarController_Tests' do
    inherit! :search_paths

    
  end
end
